spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        use_sql_comments: true
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:postgresql://host.docker.internal/nofkdemo
    username: admin
